accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import SignupView

app_name = 'accounts'
urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignupView.as_view(), name='signup'),
]

book/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index_view, name='index'),
    path('book/', views.ListBookView.as_view(), name="list-book"),
    path('book/<int:pk>/detail/', views.DetailBookView.as_view(), name="detail-book"),
    path('book/create/', views.CreateBookView.as_view(), name='create-book'),
    path('book/<int:pk>/delete/', views.DeleteBookView.as_view(), name='delete-book'),
    path('book/<int:pk>/update/', views.UpdateBookView.as_view(), name='update-book'),
    # path('logout/', views.logout_view, name='logout')
    path('book/<int:book_id>/review/', views.CreateReviewView.as_view(), name='review')
]

bookproject/urls.py
from django.contrib import admin
from django.urls import path, include

# 静的なファイルを扱うためのライブラリ
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include('accounts.urls')),
    path("", include('book.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

book/models.py
from django.db import models
# ReviewView
from .consts import MAX_RATE
RATE_CHOICES =[(x, str(x)) for x in range(0, MAX_RATE+1)]
# Create your models here.
# class SampleModel(models.Model):
#     title = models.CharField(max_length=100)
#     number = models.IntegerField()

CATEGORY = (
    ('business', 'ビジネス'),
    ('life', '生活'),
    ('other', 'その他')
)

class Book(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    thumbnail = models.ImageField(null=True, blank=True)
    category = models.CharField(
        max_length=100,
        choices = CATEGORY
    )

    # 自分で投稿したデータしか編集・削除できないようにする
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    
    # 特殊メゾット
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '本のデータ'


class Review(models.Model):
    book = models.ForeignKey(Book, on_delete = models.CASCADE)
    title = models.CharField(max_length=100)
    text = models.TextField()
    rate = models.IntegerField(choices = RATE_CHOICES)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    # UserCreationFormはModelForm
    class Meta:
        model = User
        fields =('username',)
        

accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import SignupForm

class SignupView(CreateView):
    model = User
    form_class = SignupForm #CreateViewで使うモデルを定義する（指定がなければ自動生成）
    template_name = 'accounts/signup.html'
    success_url =reverse_lazy('index')

book/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from .models import Book, Review
from django.urls import reverse_lazy, reverse
from django.db.models import Avg
from django.core.paginator import Paginator
from .consts import ITEM_PER_PAGE
# from django.contrib.auth import logout

# Create your views here.
class ListBookView(LoginRequiredMixin, ListView):
    template_name = 'book/book_list.html'
    model = Book
    paginate_by = ITEM_PER_PAGE


class DetailBookView(LoginRequiredMixin, DetailView):
    template_name = 'book/book_detail.html'
    model = Book

class CreateBookView(LoginRequiredMixin, CreateView):
    template_name = 'book/book_create.html'
    model = Book
    fields = ("title", "text", "category", "thumbnail")
    success_url = reverse_lazy('list-book')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class DeleteBookView(LoginRequiredMixin, DeleteView):
    template_name = 'book/book_confirm_delete.html'
    model = Book
    success_url = reverse_lazy('list-book')

class UpdateBookView(LoginRequiredMixin, UpdateView):
    template_name = 'book/book_update.html'
    fields = ('title', 'text', 'category', 'thumbnail')
    model = Book
    success_url = reverse_lazy('list-book')

    def get_object(self, queryset = None):
        # データベースのデータを取得
        obj = super().get_object(queryset)
        # データを作ったUserが現在のログインユーザーとは異なる場合、編集できないエラーを出す
        # Permission ForbiddenはDjangoがデフォルトで用意したエラー。
        if obj.user != self.request.user:
            raise PermissionDenied
        return obj

    # データを更新した後に飛ぶページを作成
    def get_success_url(self):
        return reverse('detail-book', kwargs = {'pk':self.object.id})



def index_view(request):
    # print('index_view is called')
    object_list = Book.objects.order_by("-id")

    # オブジェクト順に並べ替える
    ranking_list = Book.objects.annotate(avg_rating=Avg('review__rate')).order_by('-avg_rating')
    
    
    # ページネーションの実装
    pagenator = Paginator(ranking_list, ITEM_PER_PAGE)
    page_number = request.GET.get('page', 1)
    page_obj = pagenator.page(page_number)
    
    return render(
        request, 
        'book/index.html', 
        {'object_list':object_list, 'ranking_list':ranking_list, 'page_obj':page_obj}
    )



# def logout_view(request):
#     logout(request)
#     return redirect('index')


class CreateReviewView(LoginRequiredMixin, CreateView):
    model = Review
    fields=('book', 'title', 'text', 'rate')
    template_name = 'book/review_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['book'] = Book.objects.get(pk=self.kwargs['book_id'])
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('detail-book', kwargs={'pk':self.object.book.id})

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}アカウント作成{% endblock %}
{% block h1 %}アカウント作成{% endblock %}

{% block content %}
    <form method="post" class="p-4 m-4 bg-light border border-success rounded form-group">
        {% csrf_token %}
        <input type="text" name="'username" class="'form-control my-4" placeholder="ユーザー ID">
        <input type="password" name="'password1" class="'form-control mt-4" placeholder="パスワード">
        <input type="password" name="password2" class="'form-control mt-4" placeholder="パスワード確認用">

        <small class="mb-2 d-block text-start">パスワードは8文字以上で指定して下さい</small>
        {% if form.errors %}
        <span class="mb-2 small text-danger d-block text-start">
            利用できないユーザーID や パスワードの可能性があります。入力内容を再度ご確認ください。
        </span>
        {% endif %}
        <button type="submit" class="btn btn-success m-2">アカウント作成</button>
    </form>
    {% endblock %}

book/templates/book/book_confirm_delete.html
{% extends 'base.html'%}

{% block title %}書籍作成{% endblock %}

{% block content %}
    <form method ='post'>
        {% csrf_token %}
        <button type="'submit">{{ object.title }}を削除する</button>
    </form>
{% endblock content %}

book/templates/book/book_create.html
{% extends 'base.html'%}
{% block title %}書籍作成{% endblock %}
{% block content %}
    <form 
        method ='POST'
        enctype="multipart/form-data"
        class="p-4 m-4 bg-light border border-success rounded form-group">
        
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="作成する">
    </form>
{% endblock content %}

book/templates/book/book_detail.html
{% extends 'base.html' %}

{% block title %} {{ object.title }} {% endblock %}
{% block h1 %} 書籍詳細 {% endblock %}

{% block content %}
    <div class="p-4 m-4 bg-light border border-success rounded ">
        <h2 class="text-success">{{object.title}}</h2>
        <p>{{object.text}}</p>
        <img src="{{ object.thumbnail.url }}" />
        <br>
        <br>
        <div class="border p-4 mb-2">
            {% for review in object.review_set.all %}
                <div>
                    <h3 class="h4">{{ review.title }}</h3>
                    <div class="px-2">
                        <span>(投稿ユーザ: {{ review.user.username }})</span>
                        <h6>評価:{{ review.rate }}点</h6>
                        <p>{{ review.text }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
        <br>
        <br>
        <a href = "{% url 'list-book' %}" class="btn btn-primary">一覧</a>
        <a href="{% url 'review' object.pk %}" class="btn btn-primary">レビューする</a>
        <a href = "{% url 'update-book' object.pk %}" class="btn btn-primary">編集する</a>
        <a href = "{% url 'delete-book' object.pk %}" class="btn btn-primary">削除する</a>
        <h6 class="'card-title">{{object.category}}</h6>
        </div>
    </div>

{% endblock content %}

book/templates/book/book_list.html
{% extends 'base.html' %}
{% block title %}
  書籍一覧
{% endblock %}

{% block h1 %}
書籍一覧
{% endblock %}

{% block content %}
  {% for item in object_list %}
    <div class="p-4 m-4 bg-light border border-success rounded">
        <h5 class="text-success">{{ item.title }}</h5>
        <h6>カテゴリ：{{ item.category }}</h6>
        
        <div class="mt-3">
          <!-- リンクを設定する -->
          <a href="{% url 'detail-book' item.pk %}" >詳細へ</a>
        </div>
    </div>
  {% endfor %}
  {% include 'book/components/pagination.html'%}
{% endblock content %}

book/templates/book/book_update.html
{% extends 'base.html'%}

{% block title %}書籍作成{% endblock %}
{% block content %}
<form 
    method ='POST'
    enctype="multipart/form-data"
    class="p-4 m-4 bg-light border border-success rounded form-group">
        {% csrf_token %}
        {{form.as_p}}
        <button type="'submit">修正する</button>
</form>

{% endblock content %}

book/templates/book/components/pagination.html
{% if page_obj.has_other_pages %}

<ul class="list-unstyled m-0 d-flex justify-content-between">
    {% if page_obj.has_previous %}
        <li><a href="?page={{ page_pbj.previous_page_number }}">&lt;&lt;前へ</a></li>
    {% else %}
        <li class="text-muted">&lt;&lt;前へ</li>
    {% endif %}

    {% if page_obj.next_page_number %}
        <li><a href="?page={{ page_obj.next_page_number }}">次へ&gt;&gt;</a></li>
    {% else %}
        <li class="text-muted">次へ&gt;&gt;</li>
    {% endif %}
</ul>

{% endif %}

book/templates/book/index.html
{% extends 'base.html' %}

{% block title %}書籍一覧{% endblock %}
{% block h1 %}書籍一覧{% endblock %}

{%block content %}
<div class="row">
    <div class="col-9">
        {% for item in object_list %}
            <div class="p-4 m-4 bg-light border border-success rounded">
                <h2 class = "text-success">{{ item.title }}</h2>
                <img src="{{item.thumbnail.url}}"/>
                <h6>カテゴリ：{{item.category}}</h6>
                <div class="mt-3">
                    <a href="{% url 'detail-book' item.pk %}">詳細へ</a>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="col-3">
        <h2>評価準TOP2</h2>
        {% for ranking_book in page_obj %}
            <div class="p-4 m-4 bg-light border border-success rounded">
                <h3 class="text-success h5">{{ranking_book.title}}</h3>
                <img src="{{ranking_book.thumbnail.url}}" class="img-thumbnail" />
                <h6>評価:{{ranking_book.avg_rating|floatformat:2}}点</h6>
                <a href="{% url 'detail-book' ranking_book.id %}">詳細を見る</a>
            </div>
        {% endfor %}
        {% include 'book/components/pagination.html'%}
    </div>
</div>
{% endblock content %}

book/templates/book/review_form.html
{% extends 'base.html' %}
{% block title %}レビュー投稿{% endblock %}
{% block h1 %}レビュー投稿{% endblock %}

{% block content %}
<form method="post" class='p-4 m-4 bg-light border border-success rounded form-group'>
    {% csrf_token%}
    <!-- 各タグにname属性を入れてReviewモデルを参照する -->
    <label>対象書籍</label>
    <input class="form-control" value="{{ book.title }}" readonly>
    
    <label>タイトル</label>
    <input class="form-control" name="title">
    
    <label>本文</label>
    <textarea class="form-control" name="text" rows="3"></textarea>
    
    <label>星の数</label>
    <select class="form-control" name="rate">
        <option value="0">0(最低)</option>
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3(普通)</option>
        <option value="4">4</option>
        <option value="5">5(最高)</option>
    </select>
    
    <input type="hidden" name="book" value="{{book.id}}">
    <button type="submit" class="btn btn-success mt-4">投稿する</button>
</form>
{% endblock %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.rtl.min.css" integrity="sha384-WJUUqfoMmnfkBLne5uxXj+na/c7sesSJ32gI7GfCk4zO4GthUKhSEGyvQ839BC51" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'book/css/style.css' %}">
    <title>{% block title %}{% endblock title %}|本棚アプリ</title>
  </head>
  
  <body>
    <nav class="'navbar navbar-dark bg-success sticky-top">
      <div class = "navbar-nav d-flex flex-row">
        <a class="nav-link mx-3" href="{% url 'list-book' %}">書籍一覧</a>
        <a class="nav-link mx-3" href="{% url 'create-book' %}">書籍登録</a>
      </div>

      <div class="navbar-nav d-flex flex-row">
        <!-- request objectのuserのもつis_authenticated属性を調べてログイン済みか調べる -->
        {% if request.user.is_authenticated %}
          <a class="nav-link mx-3" href="{% url 'accounts:logout' %}">ログアウト</a>
        {% else %}
          <a class="nav-link mx-3" href="{% url 'accounts:login' %}">ログイン</a>
          <a class="nav-link mx-3" href="{% url 'accounts:signup' %}">会員登録</a>
        {% endif %}
      </div>
    </nav>

    <div class="'p-4">
      <h1>{% block h1 %}{% endblock %}</h1>
      {% block content %}{% endblock content %}
    </div>
  </body>
</html>